#!/bin/bash

# Install JupyterLab extension
jupyter labextension install @jupyterlab/toc

# Remove output from Jupyter notebooks
jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace doc/Notebooks/examples/Siberian_Heatwave.ipynb
jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace doc/Notebooks/examples/California_Fires.ipynb
jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace doc/Notebooks/examples/UK_Precipitation.ipynb
